spring.application.name=backend
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/personal_intelligence
spring.datasource.username=postgres
spring.datasource.password=Joao06pedro*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true